### ISSUE TITLE
document reason for 0.21.2 having been yanked from crates.io

### ISSUE THREAD

**Issue by decathorpe** [zonyitoo/rust-ini#148]
I just noticed that 0.21.2 was recently (i.e. 1-2 weeks ago) yanked from crates.io, but couldn't find any issue or pull request that would explain why that happened (i.e. a search for "yank" yields no relevant issues or pull requests).

We have already updated the Fedora Linux package for rust-ini to 0.21.2 a while ago, so it would be good to know for us if we need to roll back to 0.21.1 or backport some kind of bugfix.

**Comment by LecrisUT** [comment]
Found https://github.com/zonyitoo/rust-ini/issues/146 and seems to already be fixed

**Comment by zonyitoo** [comment]
Yes, it was yanked because of https://github.com/zonyitoo/rust-ini/issues/146 , which was fixed by https://github.com/zonyitoo/rust-ini/pull/147 . It may be released as v0.21.3 soon.

**Comment by zonyitoo** [comment]
v0.21.3 released.

**Comment by decathorpe** [comment]
Thank you!

Still not sure why GitHub search didn't turn up #146 when I searched for the string "yank" ...
